"""Discovery-suitability audit over the IWBTGR 1.5.3 source inventory.

Regenerates the evidence behind manifests/discovery_task_candidates.toml:
for every gameplay room, and for every 800x608 screen of it, the count of
placed instances whose hazard class is *initially hidden or deceptive* —
i.e. whose lethal behavior is not knowable from the rendered scene before
it first manifests, so a failure trajectory can genuinely improve a later
attempt (docs/discovery_benchmark_contract.md, section 4).

Classes are bucketed by HOW their lethality becomes observable, from the
source semantics in docs/iwbtgr_nonboss_mechanics.md (every class cited
there):

  intrinsic hidden  — hidden/deceptive on their own (invisible killers,
                      unarmed fire, fake blocks, shake-then-fall spikes,
                      collapse-on-stand platforms, hidden schedules, ...)
  trigger-dependent — visible statics (deliciousFruit) that become
                      ambushes only via a trigger's op program; counted
                      as hidden only on screens that also carry triggers
  visible           — lethality readable from the rendered scene
                      (static spikes, patrolling enemies, armed fire):
                      precision/timing content, NOT discovery content

Output: build/source_reports/discovery_screen_audit.json
Usage:  python scripts/audit_discovery_candidates.py
Input:  build/source_reports/iwbtgr_1_5_3.json (generated by
        `python -m tools.iwimport inventory <source_dir>`; the source
        tree itself is never committed).
"""
from __future__ import annotations

import collections
import json
import math
import os
import sys

REPORT = "build/source_reports/iwbtgr_1_5_3.json"
OUT = "build/source_reports/discovery_screen_audit.json"
SCREEN_W, SCREEN_H = 800, 608

GAMEPLAY_ROOMS = [
    "rGuy1", "rZelda", "rGraveyard", "rKraidgiefLair", "rMegaman",
    "rMetroid", "rFactoryOutskirts", "rCastlevania", "rGuyEntrance",
    "rGuyRoad", "rGuyFortress1", "rGuyLabyrinth", "rGuyFortress2",
    "rGuyTower",
]

#: classes whose hazard is hidden or deceptive by construction
#: (see docs/iwbtgr_nonboss_mechanics.md for the cited source semantics)
INTRINSIC_HIDDEN = {
    # invisible / maskless until they act
    "BoltTrap": "invisible until triggered (visible=1, vspeed=8.75)",
    "Grabby": "invisible killer hand until activated",
    "Fire": "maskless (sprite_index=-1) until armed by the chalice cascade",
    "FireChalice": "arming cascade for every Fire in the room",
    "FireSomes": "",  # guard against typos; unused
    "FireSometimes": "flickering mask; deadly frames not statically readable",
    "FireSometimesUpside": "flicker + inverted orientation",
    "metroidTrap": "touch despawns and spawns a homing Metroid",
    "KillPlane": "offscreen sweeper (hspeed=-35)",
    "triggerLockControls": "permanent control-lock gag",
    # deceptive look-alikes
    "blockNise": "non-solid 32x32 fake-block marker",
    "blockFake": "fake block; reveals at touch",
    "FakeFallingSpike": "shakes forever, never falls (decoy)",
    "EntranceTele": "exit that kills without all six orbs",
    "couchTrap": "single-use superbounce (vspeed=-30) from furniture",
    "GraveTrap": "touch-armed; kills only from anim frame 6",
    "TheSpikeYouShoot": "dormant shaking spike; must be shot, kills on touch",
    # delayed / conditional activation the first attempt cannot foresee
    "FallingSpike": "4-frame shake, then falls",
    "FallingSpike10frame": "10-frame shake, then falls",
    "FallingSpike10frameUp": "rises instead of falling",
    "FallingCave": "20-frame shake, then falls",
    "FallingBlockTrap": "shakes, falls at frame 40",
    "SpikeTrap": "triggered ceiling crusher (vspeed=36)",
    "PaintingTrap": "drops when the player passes underneath",
    "Higger": "falling painting with a swinging kill arc",
    "ErrorTrap": "fake error dialog; freeze + delayed kill",
    "WheelTrap": "triggered rolling wheel through destructibles",
    "FlyingSpike": "triggered riser",
    "GutsMan": "trigger-spawned scripted kill",
    "Hammer": "triggered fall, then becomes solid",
    "HammerTrigger": "arming trigger for the Hammer",
    "MoonSmall": "triggered falling moon",
    "Skwee": "hanging; dives on trigger toward the player's side",
    "SkweeTrigger": "arming trigger",
    "CatThing": "throws a fruit at an animation frame",
    "RoadBulletBill": "static until the cart trips BulletTrigger",
    "BulletTrigger": "cart-route trigger",
    "DumpMoment": "cart floor vanishes over the gap",
    "CartStopper": "invisible de-cart strip",
    "BiggusBrickus": "destructible columns burst on cart contact",
    "SpikeUpExtend": "rises toward the player, never retreats",
    "RevealingSpikesUp": "event risers (rise, sink 200 frames later)",
    "CycleSpikeUp": "35-frame animated mask; speed retimed by triggers",
    "CycleSpikeDown": "35-frame animated mask; speed retimed by triggers",
    # platforms whose failure mode is hidden until stood on / ridden
    "FallingFort": "solid until stood on, then falls and breaks",
    "OutskirtPlatform": "collapses on landing",
    "FallingBrick": "shakes then falls",
    "metroidPlatform": "sinks while ridden",
    "KumoPlatform": "trigger-driven drift",
    "PillarMove": "slides when triggered",
    "HillMove": "solid hill rises when triggered",
    "FallStair": "conditional solid",
    # hidden schedules / spawners
    "QuickLaser": "fires on a hidden frame table [10,140,200,210,350,400,590]",
    "QuickLaserTimer": "schedule starts on player touch",
    "FactoryYoku": "appearing-block chain with a hidden order/speed",
    "FactoryYokuController": "chain controller",
    "RealYoku": "toggling block sequence '012345'",
    "RealYokuController": "sequence controller",
    "RealYokuEndTrigger": "sequence end trigger",
    "tetrisController": "scripted terrain timeline (future schedule hidden)",
    "GhoulGenerator": "spawner; emergence points/timing unknown at first",
    "MedusaMaker": "offscreen spawner on a patrol path",
    "MedusaModifier": "recycle marker",
    "Witch": "strike windows keyed to the shadow sweep",
    "WitchShadow": "telegraph for the witch strike",
    "Lonk": "trigger-driven slash frames",
    # first-room gotchas
    "FirstRoomSpike": "first-screen gotcha spike",
    "FirstRoomSpikeWall": "gotcha marker",
    "FirstRoomBarrier": "conditional barrier",
}
INTRINSIC_HIDDEN.pop("FireSomes")

#: the trigger region class itself (invisible zones; each one arms or
#: launches something) and the classes it typically weaponizes
TRIGGER_CLASS = "trigger"
TRIGGER_DEPENDENT = {
    "deliciousFruit": "static cherry; launched (vspeed ±6.25/12.5) only "
                      "by a trigger's op program",
}


def main() -> int:
    if not os.path.exists(REPORT):
        print(f"missing {REPORT}; run `python -m tools.iwimport inventory "
              f"<source_dir>` first", file=sys.stderr)
        return 1
    src = json.load(open(REPORT, encoding="utf-8"))
    rooms = {r["name"]: r for r in src["rooms"]}
    audit: dict = {
        "format": "discovery-screen-audit/1",
        "screen_px": [SCREEN_W, SCREEN_H],
        "rooms": {},
    }
    for rn in GAMEPLAY_ROOMS:
        room = rooms[rn]
        per_screen: dict = collections.defaultdict(
            lambda: {"intrinsic": collections.Counter(),
                     "triggers": 0,
                     "trigger_dependent": collections.Counter()})
        anchors = []
        for inst in room["instances"]:
            obj = inst["object"]
            key = (int(inst["x"] // SCREEN_W), int(inst["y"] // SCREEN_H))
            if obj in INTRINSIC_HIDDEN:
                per_screen[key]["intrinsic"][obj] += 1
            elif obj == TRIGGER_CLASS:
                per_screen[key]["triggers"] += 1
            elif obj in TRIGGER_DEPENDENT:
                per_screen[key]["trigger_dependent"][obj] += 1
            if obj.startswith("save") or obj == "playerStart":
                anchors.append([obj, inst["x"], inst["y"]])
        screens = []
        for (sx, sy), rec in sorted(per_screen.items()):
            n_int = sum(rec["intrinsic"].values())
            n_dep = sum(rec["trigger_dependent"].values())
            # trigger-dependent statics count only when the screen (or the
            # audit consumer, for cross-screen trigger wiring) has triggers
            effective = n_int + (n_dep if rec["triggers"] > 0 else 0)
            cx, cy = sx * SCREEN_W + SCREEN_W / 2, sy * SCREEN_H + SCREEN_H / 2
            anchor = None
            if anchors:
                a = min(anchors,
                        key=lambda t: math.hypot(t[1] - cx, t[2] - cy))
                anchor = {"object": a[0], "x": a[1], "y": a[2]}
            screens.append({
                "screen": [sx, sy],
                "intrinsic_hidden": dict(rec["intrinsic"]),
                "triggers": rec["triggers"],
                "trigger_dependent": dict(rec["trigger_dependent"]),
                "discovery_evidence": effective,
                "nearest_anchor": anchor,
            })
        audit["rooms"][rn] = {
            "dims_px": [room["width"], room["height"]],
            "room_speed": room["speed"],
            "screens": screens,
            "totals": {
                "intrinsic_hidden": sum(
                    sum(s["intrinsic_hidden"].values()) for s in screens),
                "triggers": sum(s["triggers"] for s in screens),
                "trigger_dependent": sum(
                    sum(s["trigger_dependent"].values()) for s in screens),
            },
        }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(audit, f, indent=1, sort_keys=True)
    for rn in GAMEPLAY_ROOMS:
        t = audit["rooms"][rn]["totals"]
        print(f"{rn:20s} intrinsic={t['intrinsic_hidden']:4d} "
              f"triggers={t['triggers']:3d} "
              f"trigger_dep={t['trigger_dependent']:4d}")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
