"""Inspect an exact-game room graph independently of the runtime.

    python scripts/inspect_game_graph.py [--game iwbtgr_1_5_3]
        [--json out.json]   machine-readable adjacency report
        [--dot out.dot]     Graphviz digraph
        [--montage out.png] low-cost debug montage of room geometry
                            (needs the locally built pack; schematic only)

Reads the committed room_graph.json — no source files, no pack, no C
library required (except --montage).
"""
from __future__ import annotations

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))


def adjacency(g: dict) -> dict:
    adj: dict[str, list] = {}
    for e in g["edges"]:
        adj.setdefault(e["from"], []).append({
            "to": e["to"], "via": e["via"], "mode": e["mode"],
            "condition": e["condition"], "lowered": e["lowered"],
        })
    return adj


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--game", default="iwbtgr_1_5_3")
    ap.add_argument("--json")
    ap.add_argument("--dot")
    ap.add_argument("--montage")
    ap.add_argument("--md", help="write the room-graph markdown doc here")
    args = ap.parse_args()

    from iwanna_gym.games import get_game
    G = get_game(args.game)
    g = G.graph()
    adj = adjacency(g)

    print(f"{args.game}: {len(g['rooms'])} rooms, {len(g['edges'])} edges, "
          f"start={g['start_room_full_game']}")
    for r in g["rooms"]:
        outs = adj.get(r["name"], [])
        meta = " [meta]" if r["meta_room"] else ""
        print(f"  [{r['id']:2d}] {r['name']:20s} {r['px'][0]}x{r['px'][1]}px"
              f"{meta}  saves M/H/VH: "
              f"{r['saves_by_difficulty']['medium']}/"
              f"{r['saves_by_difficulty']['hard']}/"
              f"{r['saves_by_difficulty']['very_hard']}")
        for o in outs:
            cond = ""
            if o["condition"]:
                cond = f"  IF {o['condition']}" + \
                       ("" if o["lowered"] else "  (not lowered)")
            print(f"        -> {o['to']:20s} via {o['via']}/{o['mode']}{cond}")
        for s in r.get("scripted_transitions", []):
            print(f"        ~> scripted: {s} (dynamic, not imported)")
    print("reachable without flags:", len(g["reachable_without_flags"]),
          "| with flags+scripts:",
          len(g["reachable_with_all_flags_and_scripts"]),
          "| orphaned required rooms:", g["orphaned_required_rooms"] or "none")

    if args.json:
        with open(args.json, "w") as f:
            json.dump({"game": args.game, "adjacency": adj,
                       "rooms": g["rooms"]}, f, indent=1)
        print("wrote", args.json)
    if args.dot:
        with open(args.dot, "w") as f:
            f.write("digraph iwbtgr {\n  rankdir=LR;\n")
            for r in g["rooms"]:
                shape = "box" if not r["meta_room"] else "ellipse"
                f.write(f'  "{r["name"]}" [shape={shape}];\n')
            for e in g["edges"]:
                style = ' [style=dashed,label="cond"]' if e["condition"] else ""
                f.write(f'  "{e["from"]}" -> "{e["to"]}"{style};\n')
            f.write("}\n")
        print("wrote", args.dot)
    if args.md:
        with open(args.md, "w") as f:
            f.write(markdown(args.game, g, adj))
        print("wrote", args.md)
    if args.montage:
        montage(G, g, args.montage)
        print("wrote", args.montage)
    return 0


def markdown(game: str, g: dict, adj: dict) -> str:
    L = ["<!-- GENERATED by scripts/inspect_game_graph.py --md from the "
         "committed room_graph.json — do not hand-edit. -->", "",
         f"# {game} room graph", "",
         f"{len(g['rooms'])} rooms in source resource-tree order; "
         f"{len(g['edges'])} transition edges parsed mechanically from warp "
         "creation code and EntranceTele's events "
         "(iwanna_gym/games/iwbtgr_1_5_3/converter.py). Full-game start: "
         f"**{g['start_room_full_game']}** (menus are meta rooms). The "
         "machine-readable graph is `iwanna_gym/games/iwbtgr_1_5_3/"
         "room_graph.json`; inspect with `python scripts/"
         "inspect_game_graph.py`.", "",
         "| # | room | size (px) | kind | saves M/H/VH | transitions out |",
         "|---|---|---|---|---|---|"]
    for r in g["rooms"]:
        outs = []
        for o in adj.get(r["name"], []):
            s = f"{o['to']}"
            if o["condition"]:
                key = o["condition"].get("savedata") or "6 orbs"
                s += f" (if {key}{'' if o['lowered'] else '; not lowered'})"
            outs.append(s)
        for s in r.get("scripted_transitions", []):
            outs.append(f"~{s} (scripted, dynamic)")
        sv = r["saves_by_difficulty"]
        L.append(f"| {r['id']} | {r['name']} | {r['px'][0]}×{r['px'][1]} | "
                 f"{'meta' if r['meta_room'] else 'gameplay'} | "
                 f"{sv['medium']}/{sv['hard']}/{sv['very_hard']} | "
                 f"{', '.join(outs) or '—'} |")
    L += ["",
          f"Reachability from {g['start_room_full_game']}: "
          f"{len(g['reachable_without_flags'])} rooms with no progression "
          f"flags; {len(g['reachable_with_all_flags_and_scripts'])} adding "
          "flag-gated and scripted (boss/ending) transitions; orphaned "
          f"required rooms: {g['orphaned_required_rooms'] or 'none'}. "
          "Rooms outside the reachable set are menus/dev/BossRush (meta).", "",
          "Progression flags (runtime gflags ids): " +
          ", ".join(f"`{k}`={v}" for k, v in g["progression_flags"].items())
          + ". The rFactoryOutskirts→rCastlevania warp re-routes after "
          "`orb_dracula` (lowered exactly, applied within 2 frames of room "
          "entry); the rGuyEntrance→rGuyRoad gate needs all six boss orbs "
          "(recorded, not lowered — AND conditions await runtime support; "
          "use `set_gflag`/room mode to inspect the palace).", "",
          "Known documented equivalences of the static import: saves are "
          "touch-activated (source: shot with the gun) and respawn at the "
          "save position (source: player position at save time); spawn "
          "side-effects (`global.castleboost` launch boost, "
          "`factory_ceiling_flag`) are recorded in the graph but not yet "
          "implemented; dynamic objects (bosses, moving hazards, walljump "
          "walls, water, yoku blocks) are excluded and listed in "
          "`build/games/iwbtgr_1_5_3.coverage.json`."]
    return "\n".join(L) + "\n"


def montage(G, g: dict, out: str, scale: int = 8) -> None:
    """Schematic geometry montage (1 px per `scale` source px): blocks
    grey, spikes red, saves green, warps violet. Debug aid only."""
    import numpy as np
    from iwanna_gym.clib import CIWanna
    pack = G.load_pack()
    cell = 4800 // scale + 8
    rows = []
    for r in g["rooms"]:
        c = CIWanna.from_pack(pack, start_room=r["id"])
        c.reset()
        t = c.tiles()
        h, w = r["px"][1] // scale, r["px"][0] // scale
        img = np.zeros((h, w, 3), np.uint8) + 18
        ty, tx = np.nonzero(t == 1)
        for k in range(0, 33, 8):
            pass
        # tiles (32px) -> blocks of 32/scale px
        s = 32 // scale if scale <= 32 else 1
        for yy, xx in zip(ty, tx):
            img[yy*s:(yy+1)*s, xx*s:(xx+1)*s] = (95, 95, 120)
        for code, col in ((2, (220, 60, 60)), (3, (220, 60, 60)),
                          (4, (220, 60, 60)), (5, (220, 60, 60))):
            ty, tx = np.nonzero(t == code)
            for yy, xx in zip(ty, tx):
                img[yy*s:(yy+1)*s, xx*s:(xx+1)*s] = col
        for x0, y0, x1, y1 in c.solids():
            img[max(0, int(y0)//scale):max(0, int(y1)//scale)+1,
                max(0, int(x0)//scale):max(0, int(x1)//scale)+1] = (130, 130, 160)
        for sh, x0, y0, x1, y1 in c.killers():
            img[max(0, int(y0)//scale):max(0, int(y1)//scale)+1,
                max(0, int(x0)//scale):max(0, int(x1)//scale)+1] = (230, 90, 90)
        for row in c.entities(2048):
            et, ex, ey = int(row[0]), int(row[1])//scale, int(row[2])//scale
            col = (90, 220, 120) if et == 8 else (180, 120, 240) if et == 9 else None
            if col and 0 <= ey < h and 0 <= ex < w:
                img[max(0, ey-2):ey+3, max(0, ex-2):ex+3] = col
        c.close()
        pad = np.zeros((h + 6, cell, 3), np.uint8)
        pad[3:3+h, 3:3+min(w, cell-6)] = img[:, :cell-6]
        rows.append(pad)
    H = sum(r.shape[0] for r in rows)
    canvas = np.zeros((H, cell, 3), np.uint8)
    y = 0
    for r in rows:
        canvas[y:y+r.shape[0]] = r
        y += r.shape[0]
    import imageio.v2 as imageio
    imageio.imwrite(out, canvas)


if __name__ == "__main__":
    raise SystemExit(main())
